### ISSUE TITLE
[BUG] Not working with @nestjs/graphql

### ISSUE THREAD

**Issue by robertwestbury** [iamolegga/nestjs-session#191] opened 2020-03-31 13:48 UTC
**What is the current behavior?**

Using @Session in a resolver dosen't work, and session is null.

**Please provide the steps to reproduce.**

Install Nest with graphql, and install this. Then, in your resolver have a @Session parameter and see what it is. It will be null.

**What is the expected behavior?**
It isn't null.

**Please mention other relevant information such as Node.js version and Operating System.**
Node 11.15.0, session configuration:
```ts
SessionModule.forRoot({
  session: {
    secret: 'temp',
    store: new RedisStore({ client: RedisConnection }),
    resave: false,
    saveUninitialized: true
  }
});
```
In my resolver:
```ts
  @Mutation(() => User)
  async register(
    @Session() session: SessionType
  ) {
    .....

    session.user = user.id; // TypeError: Cannot set property 'user' of null
  }
```

**Comment by iamolegga** [comment] 2020-03-31 14:09
Sorry, I did not get it, is this runtime error or TS error? If this is runtime error, then this is duplicate of #181 , if this is TS error, then check please your own type `SessionType`.
Closing this

**Comment by robertwestbury** [comment] 2020-03-31 14:29
I am not using passport, making it not a duplicate.

**Comment by iamolegga** [comment] 2020-03-31 20:42
Ok ok, I see now, but you did not tell, is this runtime bug or just types?

**Comment by iamolegga** [comment] 2020-04-03 06:42
@robertwestbury ?

**Comment by iamolegga** [comment] 2020-04-04 08:53
Seems like this is TS error because of your `SessionType` type, `TypeError` also saying this.
So, I'm closing this issue

**Closed by iamolegga** 2020-04-04 08:53 UTC
Labels: bug
