### ISSUE TITLE
[BUG] Depracation warnings

### ISSUE THREAD

**Issue by kkoomen** [iamolegga/nestjs-session#317] opened 2020-12-18 04:02 UTC
After integrating this into my Nest  project we ran into these warnings. Could you resolve them please?

```
Fri, 18 Dec 2020 04:00:02 GMT express-session deprecated undefined resave option; provide resave option at node_modules/nestjs-session/dist/index.js:8:22

Fri, 18 Dec 2020 04:00:02 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/nestjs-session/dist/index.js:8:22
```

**Comment by iamolegga** [comment] 2021-08-30 09:17
Closing this issue, this is not a bug, the message is absolutely clear: carefully read the docs of `express-session` and set `resave` and `saveUninitialized` fields

**Closed by iamolegga** 2021-08-30 09:17 UTC
Labels: bug
